### ISSUE TITLE
【问题】青龙面板2.15.5中提示 require() of ES modules is not supported.

### ISSUE THREAD

**Issue by klxfp** [zhenglinhui/leigod#1]
已安装node-fetch 和 js-md5版本
不知道import问题还是版本太高了
日志
  LeiGod_Acc auto pause, 开始!
/ql/data/scripts/zhenglinhui_leigod/leigod_signin.js:8
const fetch = require('node-fetch');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.local/share/pnpm/global/5/.pnpm/node-fetch@3.3.1/node_modules/node-fetch/src/index.js from /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js not supported.
Instead change the require of index.js in /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/ql/data/scripts/zhenglinhui_leigod/leigod_signin.js:8:15) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by zhenglinhui** [comment]
如果你有单独在青龙面板中安装node-fetch依赖，请移除后尝试 （无需单独安装node-fetch），有可能是版本问题

**Comment by klxfp** [comment]
感谢回复， 需要单独安装node-fetch依赖， 降低为node-fetch@2.6.2版本 问题已解决
