### ISSUE TITLE
大佬，最新版擒龙面板不能添加js-md5依赖

### ISSUE THREAD

**Issue by QmaQ** [zhenglinhui/leigod#2]
🔔LeiGod_Acc auto pause, 开始!
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'node-fetch'
Require stack:
- /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/ql/data/scripts/zhenglinhui_leigod/leigod_signin.js:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/data/scripts/zhenglinhui_leigod/leigod_signin.js' ]
}

Node.js v20.11.1

**Comment by zhenglinhui** [comment]
好久没管这个项目了，刚才使用最新的青龙版本重新安装依然正常运行，未复现此bug 。如有问题，请更具体的说明一下
![test](https://github.com/zhenglinhui/leigod/assets/67667134/bde15e2d-0744-453e-8b68-332c76c32bff)
![dependence](https://github.com/zhenglinhui/leigod/assets/67667134/d7d8ff6e-f6c4-43cd-9db2-163d5a783c5b)

**Comment by QmaQ** [comment]
![屏幕截图 2024-04-25 112336](https://github.com/zhenglinhui/leigod/assets/75363671/e2340961-9775-46f2-a478-36d78e128e96)
![屏幕截图 2024-04-25 112408](https://github.com/zhenglinhui/leigod/assets/75363671/3acd9178-56cb-4298-a54b-08c2b8b5c506)
版本现在变这样了，方便说一下一的版本吗？我换一下

**Comment by zhenglinhui** [comment]
我使用docker compose启动，可能作者并未更新 whyour/qinglong    latest    5997b3824cbe   2 years ago     434MB  
青龙面板版本为v2.10.13
你可以尝试直接拉取看查看镜像id是否一致`docker pull whyour/qinglong:latest`

**Comment by zhenglinhui** [comment]
我去作者演示网站查看了新版没什么变化，安装依赖不在系统设置中，是在依赖管理中。
![image](https://github.com/zhenglinhui/leigod/assets/67667134/9adbcb11-9471-424c-b60c-38be37b0a1a2)

**Comment by QmaQ** [comment]
我又添加了require，node-fetch这两个，还是不行，可能是群晖的docker造成的奇奇怪怪的问题吧
## 开始执行... 2024-04-25 20:06:46


🔔LeiGod_Acc auto pause, 开始!
/ql/data/scripts/zhenglinhui_leigod/leigod_signin.js:8
const fetch = require('node-fetch');
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.local/share/pnpm/global/5/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js from /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js not supported.
Instead change the require of index.js in /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/ql/data/scripts/zhenglinhui_leigod/leigod_signin.js:8:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.11.1

## 执行结束... 2024-04-25 20:06:46  耗时 1 秒

**Comment by zhenglinhui** [comment]
> 我又添加了require，node-fetch这两个，还是不行，可能是群晖的docker造成的奇奇怪怪的问题吧
> 
> ## 开始执行... 2024-04-25 20:06:46
> 🔔LeiGod_Acc auto pause, 开始! /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js:8 const fetch = require('node-fetch'); ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.local/share/pnpm/global/5/.pnpm/node-fetch@3.3.2/node_modules/node-fetch/src/index.js from /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js not supported. Instead change the require of index.js in /ql/data/scripts/zhenglinhui_leigod/leigod_signin.js to a dynamic import() which is available in all CommonJS modules. at Object. (/ql/data/scripts/zhenglinhui_leigod/leigod_signin.js:8:15) { code: 'ERR_REQUIRE_ESM' }
> 
> Node.js v20.11.1
> 
> ## 执行结束... 2024-04-25 20:06:46 耗时 1 秒

不需要添加 node-fetch 只需要添加 js-md5依赖即可，先确认青龙面板是否已正常安装

**Comment by catsimple** [comment]
第八行
`const fetch = require('node-fetch');`
改成
`const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));`
